steps:
# Build the integration manager image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ccwintegrationmanager', '-f', 'src/ChildcareWorldwide.Integration.Manager/Dockerfile', '.']
# Build the integration subscriber image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ccwintegrationsubscriber', '-f', 'src/ChildcareWorldwide.Integration.Subscriber/Dockerfile', '.']

# Push the container images to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ccwintegrationmanager']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ccwintegrationsubscriber']


# Deploy container images to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ccw-integration-manager', '--image', 'gcr.io/$PROJECT_ID/ccwintegrationmanager', '--region', 'us-west1', '--platform', 'managed', '--allow-unauthenticated']
# Only one of these will succeed
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', 'gcloud compute instances create-with-container ccw-integration-subscriber --machine-type=f1-micro --zone=us-west1-a --container-image=gcr.io/$PROJECT_ID/ccwintegrationsubscriber --scopes=default,cloud-platform || exit 0']
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/bash'
  args: ['-c', 'gcloud compute instances update-container ccw-integration-subscriber --zone=us-west1-a --container-image=gcr.io/$PROJECT_ID/ccwintegrationsubscriber || exit 0']


images:
- 'gcr.io/$PROJECT_ID/ccwintegrationmanager'
- 'gcr.io/$PROJECT_ID/ccwintegrationsubscriber'
